# Generated by Django 2.1.1 on 2018-09-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppGlobalId',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID作为用户ID')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '全局自增ID',
                'verbose_name_plural': '全局自增ID',
                'db_table': 'app_global_id',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(0)',
                'verbose_name_plural': '用户ID映射openid加plat(0)',
                'db_table': 'app_uid_openid0',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(1)',
                'verbose_name_plural': '用户ID映射openid加plat(1)',
                'db_table': 'app_uid_openid1',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(2)',
                'verbose_name_plural': '用户ID映射openid加plat(2)',
                'db_table': 'app_uid_openid2',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(3)',
                'verbose_name_plural': '用户ID映射openid加plat(3)',
                'db_table': 'app_uid_openid3',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(4)',
                'verbose_name_plural': '用户ID映射openid加plat(4)',
                'db_table': 'app_uid_openid4',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(5)',
                'verbose_name_plural': '用户ID映射openid加plat(5)',
                'db_table': 'app_uid_openid5',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(6)',
                'verbose_name_plural': '用户ID映射openid加plat(6)',
                'db_table': 'app_uid_openid6',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid7',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(7)',
                'verbose_name_plural': '用户ID映射openid加plat(7)',
                'db_table': 'app_uid_openid7',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid8',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(8)',
                'verbose_name_plural': '用户ID映射openid加plat(8)',
                'db_table': 'app_uid_openid8',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUidOpenid9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增id')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='用户ID')),
                ('openid', models.CharField(max_length=32, verbose_name='用户在第三方平台的ID')),
                ('plat', models.PositiveSmallIntegerField(verbose_name='第三方平台ID，自定义')),
                ('create_time', models.PositiveIntegerField(verbose_name='写入时间')),
            ],
            options={
                'verbose_name': '用户ID映射openid加plat(9)',
                'verbose_name_plural': '用户ID映射openid加plat(9)',
                'db_table': 'app_uid_openid9',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo0',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(0)',
                'verbose_name_plural': '用户信息(0)',
                'db_table': 'app_userinfo0',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo1',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(1)',
                'verbose_name_plural': '用户信息(1)',
                'db_table': 'app_userinfo1',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo2',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(2)',
                'verbose_name_plural': '用户信息(2)',
                'db_table': 'app_userinfo2',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo3',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(3)',
                'verbose_name_plural': '用户信息(3)',
                'db_table': 'app_userinfo3',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo4',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(4)',
                'verbose_name_plural': '用户信息(4)',
                'db_table': 'app_userinfo4',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo5',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(5)',
                'verbose_name_plural': '用户信息(5)',
                'db_table': 'app_userinfo5',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo6',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(6)',
                'verbose_name_plural': '用户信息(6)',
                'db_table': 'app_userinfo6',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo7',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(7)',
                'verbose_name_plural': '用户信息(7)',
                'db_table': 'app_userinfo7',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo8',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(8)',
                'verbose_name_plural': '用户信息(8)',
                'db_table': 'app_userinfo8',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo9',
            fields=[
                ('uid', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.PositiveSmallIntegerField(default=2, verbose_name='性别')),
                ('usersig', models.CharField(default='0', max_length=100, verbose_name='个性签名')),
                ('userarea', models.CharField(default='0', max_length=100, verbose_name='所在区域')),
                ('regtime', models.PositiveIntegerField(verbose_name='注册时间')),
                ('entercount', models.PositiveIntegerField(verbose_name='登录天数')),
                ('entertme', models.PositiveIntegerField(verbose_name='最近一天第一次登录的时间')),
            ],
            options={
                'verbose_name': '用户信息(9)',
                'verbose_name_plural': '用户信息(9)',
                'db_table': 'app_userinfo9',
                'abstract': False,
            },
        ),
    ]
